Add get_history() feature
flagist0/reverso_context_api pull request #1
Opened 2020-12-18 17:31 UTC by aykim17

I added a feature to pull a user's Reverso Context search history. I found it useful and thought others might as well.

2020-12-21 19:33 UTC, flagist0 requested changes
Thank you for the pull request! I found couple of problems in the code. Unfortunately one of them doesn't let the code execute

2020-12-21 19:33 UTC, flagist0 commented on reverso_context_api/client.py
> +                yield self._process_history_entry(entry, cleanup)
`cleanup` is not defined in this context

2020-12-21 19:33 UTC, flagist0 commented on reverso_context_api/client.py
> +    def _process_history_entry(self, entry, cleanup):
`cleanup` is not used by the code, so it's better to remove it

2020-12-21 19:33 UTC, flagist0 commented on reverso_context_api/client.py
> +            "translation1": "translation_1",
All translation variants are returned in fields "translationN". There can be many of them, I think they have to be extracted and put into list field "translations". Also sometimes there are even empty values, which have to be removed.

2020-12-27 10:32 UTC, flagist0 commented
Ok, I've fixed the problems

2020-12-27 10:32 UTC, merged

2021-01-03 17:13 UTC, aykim17 commented
Sorry for the late reply and buggy submission- glad you were able to get it working!